### ISSUE TITLE
Add snapshot tests for iOS 16 and audit results

### ISSUE THREAD

**Issue by NickEntin** [cashapp/AccessibilitySnapshot#117]
* Add iOS 16 to our build script and record new reference images
* Update the CI config to include an iOS 16 build
* Audit the reference images against VoiceOver on a device running iOS 16 and file issues for any changes/regressions where the behavior doesn't match

**Comment by pwesten** [comment]
Adding iOS 16 to our project's test config yielded many new crosshair overlays on buttons. There may be a pixel-rounding change that `AccessibilityHierarchyParser.defaultActivationPoint(for: )` needs to take into account. And on that note, that method could be sensitive to text fields that are first responder (where the activation point is on the insertion bar rather than the center of the view).
