### ISSUE TITLE
Discuss: Remove tight coupling on Uber library to improve flexibility

### ISSUE THREAD

**Issue by Sherlouk** [cashapp/AccessibilitySnapshot#3]
First off can I say what a great library you've built already - it's a problem I've been looking to solve for a while now and this is making some great progress to what I've pictured!

My one problem at the moment is that we personally use a different snapshot library (specifically [this one](https://github.com/pointfreeco/swift-snapshot-testing) from Pointfree!) and this library is, presumably because it's what you use, is tied to [Uber/Facebooks Snapshot Library](https://github.com/uber/ios-snapshot-test-case).

I'm curious if you would be open to breaking the project down some? I picture some sort of "core" module which is responsible for all the accessibility hierarchy parsing and even some of the image creation but then I think it would be nice if the snapshot library specific code could go in a separate modules?

So you may end up with the following specs (in a pods world):
`AccessibilitySnapshot` which is the core parsing and image generation (but no snapshot dependencies)
`AccessibilitySnapshot/iOSSnapshotTestCase` which is the Uber/FB specific extensions

and the community could work together to supply a
`AccessibilitySnapshot/Pointfree` which is the Pointfree extensions?

Open to discussion/thoughts on all of this though!

**Comment by NickEntin** [comment]
Thanks! Glad to hear you like the project and are interested in using it!

I definitely considered pulling the core parser out into a subspec originally, but I wanted to keep it simple to begin with and see where there was interest to adapt it. I think having the initial setup process be super straightforward for new developers is key.

The main question in my mind is whether the framework should expose different implementations as subspecs; or expose the core parser in the public API and a single optional integration layer on top, while integration with other snapshot frameworks would live in separate projects. There are some pros and cons to each.

Different implementations as subspecs:
* Consumers only have to add one dependency. We can default to the `[Core, iOSSnapshotTestCase]` subspecs so that the initial setup process is still super quick, but can be customized by setting which subspecs to include.
* Gives us the option of keeping the core parser internal. The smaller the public API, the larger the changes we can make without it being a breaking change. Quite possible we would want to expose this in the public API anyway, but at least we would have the choice.
* Potentially adds a lot of dependencies to this project as the number of integrations grows, which likely means an increased rate of breaking changes propagated up from dependencies that consumers might not actually be using.

Core parser exposed, with different implementations in separate projects:
* Consumers have to add multiple dependencies if they choose to use something other than the default integration. Not necessarily a big problem, but we'd lose the single source of truth for what's available, and there might be a delay in getting bug fixes out if the other projects need to be updated as well.
* The core parser would need to be part of the public API. Again, not necessarily a bad thing, but something to keep in mind.

One thing I noticed in the [Twitter thread](https://twitter.com/basthomas/status/1263835904453591045) was talking about pulling out a textual representation. I think this is a good argument for exposing the core parser. Originally I had thought about having the framework output two files - a snapshot image with the highlighted regions and a text file with the descriptions - but that increases the complexity a bit and opens up the potential for those files to get out of sync. I briefly considered creating a custom file format that contained the image data as well as structured marker data, but that would require a special viewer and would break diffing on hosted git services.

Very long answer to your question, but yes! Definitely open to breaking the project down into separate layers. Very curious to hear what ways people would like to use it and how we could best support that.

**Comment by Sherlouk** [comment]
Hi Nick, I appreciate the detailed response there - it's great to see you're open to _something_ like this!

> I think having the initial setup process be super straightforward for new developers is key.

I definitely agree and this sentiment should be carried through no matter the approach - though I think it is important to measure what "super straightforward" actually means. 

I don't say this defensively but just as a bit of "devils advocate" but if a user was required to add, say, two lines to their `Podfile` (or `Package.swift`, etc) is that not still straightforward enough?

---

It seems from your message we can reduce the primary questions to how much of the interface you want public and how much you would want to bloat the primary repository. Let's break them down:

> how much of the interface you want public

Now the issue here is that with a larger public API you become susceptible to more of your releases being a breaking change which in turn makes it more difficult for the developers who implement the library.

But on the positive side it's been highlighted that there's a potential eagerness from some people to have more of the API public so they can do their own textual representations (amongst other things).

The balance here is of course between safety and simplicity vs flexibility and control. I feel like testing is one of those things where everybody does it _slightly_ differently and so I feel flexibility/control wins out here but I can see the argument to keep it as simple as possible too...

This also only really becomes a problem (as you state) if we entirely split the sub-modules out of the repo... which brings us onto the second concern

> how much you would want to bloat the primary repository

If we were to keep everything within one repo then we have a lot more flexibility over what needs to be public and what can stay internal -- even if a sub-module needs access to that data it doesn't necessarily need to be public.

The concern is though of how many snapshot libraries do we want to support? In my original comment I raise wanting to support Pointfree's library (as well as Uber's) but more exist and more will come. While it may seem reasonable to just add support in the repo for now this can soon get out of control -- since people are unable to release their own sub-modules you risk having many different forks or this same issue being raised again in the future.

You mention how it could be a concern that it's slow to receive bug fixes if the repo is broken down and to an extent this is true but also I think this comes down to being very clear about "officially" supported vs "community" supported. If you're accepting that you support Uber's library and the core one then people can understand they'll get quick support there (and there's no major harm in leaving the "official" stuff in the same repo for clarity) and things will be updated quickly but the same isn't necessarily true for community led things.

---

Now I haven't looked at enough of the code to make a final statement here but it does seem to all balance on the question of "bloating the interface vs bloating the codebase". 

I don't know how much of the codebase needs to be public in order for the Uber stuff to be optional so I'm not sure how much that side of the argument is weighted.

Equally we don't know how many libraries the community may end up wanting supporting so if the option was to simply "bloat for now" this issue may very well rise again in a couple months when someone asks can you support "MegaAppleSnapshotter 2.0"!

@NickEntin - are you able to quantify at all how much of the codebase would need to be public (in comparison to what already is public) in order for Uber to be pulled out? That seems to be the biggest unknown from my perspective here!

**Comment by NickEntin** [comment]
Thanks James, I appreciate the thoughtful response. The more I look into it, the more I may have overestimated the complexity here. I've done a fair amount of refactoring since I last looked into it, and I think that's actually made it much more straightforward. 😄 

I opened a draft PR (#5) to split the framework into two subspecs. The main types in the Core subspec that the integration layer will need to interact with for showing a breakdown of the accessibility hierarchy are:

* `AnimationSnapshotView` - This is a container around the view being snapshotted that contains a snapshot of the view and the views that make up the highlights and legend. This is the only class the integration layer needs to interact with to output snapshot images of the accessibility hierarchy.
* `AccessibilityHierarchyParser` - This is where all of the parsing logic lives. It has a single exposed method that returns an array of accessibility markers. This is the only class the integration layer needs to interact with to get the raw data behind the snapshot image (e.g. for a textual representation).

I think it's important to note that the `AccessibilityHierarchyParser` (or specifically the data structures it returns) is probably the area that has gone through the most iterations. I often had to rework the structures when adding support for a new accessibility property/feature to get it to represent the data correctly. Hopefully it will be pretty stable now, but only time will tell.

Other than that, I don't think it would be a big deal to make these classes (and the associated data structures) public.

There are also a few points of interaction for snapshotting with inverted color and (the currently in-progress #4) dynamic type:

* `UIAccessibilityStatusUtility` - This is used to mock the Invert Colors setting.
* `UIView.drawHierarchyWithInvertedColors(in:using:)` - This extension does the actual drawing.
* `UIView+DynamicTypeSnapshotting`/`UIApplication+DynamicTypeSnapshotting` - These are used to mock the Dynamic Type setting.

> The concern is though of how many snapshot libraries do we want to support?

This is the main question in my mind. I think having two snapshot integrations (plus maybe a third text-only version) is reasonable. My worry is around, as you mentioned, the high likelihood that the number of integrations will grow over time.

Overall, I think my preference is that we break into two subspecs and make the above types public in the Core subspec. This repo will contain the core parser engine and a single officially supported integration with iOSSnapshotTestCase. Other community supported integrations can then live in separate repos and have 'AccessibilitySnapshot/Core' as a dependency. I'm happy to include a list of those integrations in the README here.

Does that sound reasonable?

**Comment by Sherlouk** [comment]
Sorry Nick, was MIA yesterday so only just getting around to this... 

Amazing work with the draft PR, I've taken a look at the branch and it's surprisingly exciting and how few changes were necessary to get that functional!

Those quick descriptions of what each class does might be a great candidate for an `architecture.md` or a page on the wiki - very helpful for getting quickly on board of what each part of the codebase is for.

I agree with your preference at the bottom though - it feels like that's the smallest subset of changes and doesn't dramatically affect CashApp or the maintainability of this repository since the scope is pretty much the same but does enable the community to publish their own extensions! A sensible compromise!

Perhaps once you've made the necessary changes of making parts of Core public, we/I can investigate adding Pointfree support (in a separate repository) as a proof of concept that everything works? Would be a good confirmation piece to make sure everything is working as expected!

Really appreciate your openness and quick moving to support this

**Comment by NickEntin** [comment]
No worries! I've updated #5 so it should have everything listed above marked as public.

> Those quick descriptions of what each class does might be a great candidate for an architecture.md or a page on the wiki

Great idea! I'll put together a wiki page that goes over the major components in the framework.

> Perhaps once you've made the necessary changes of making parts of Core public, we/I can investigate adding Pointfree support (in a separate repository) as a proof of concept that everything works? Would be a good confirmation piece to make sure everything is working as expected!

Definitely agreed. Do you want to start putting together a proof of concept? Happy to help out if there are problems with the integration.

**Comment by Sherlouk** [comment]
Awesome work Nick!

Sure thing, just reinstalling a new machine but once that's done I'll give it a go and see where I come to! Will post updates when I have them...

**Comment by Sherlouk** [comment]
Okay so I spent a lovely 30 minutes debugging a missing import (yay for helpful Xcode errors 😂) but I've got this... [Sherlouk/AccessiiblitySnapshotPointfree](https://github.com/Sherlouk/AccessiiblitySnapshotPointfree).

I lifted most of this repo and just worked from there including keeping the entire SnapshotTests directory (of course replacing all `SnapshotVerify` calls to `verifySnapshot` calls as per the Pointfree syntax).

Need to do a documentation sweep and all that jazz but tests all seem to be running and passing.

@NickEntin - Would you mind taking a quick look, especially at the test outputs (which are in `Example/SnapshotTests/__Snapshots__`) to make sure things are generating correctly? I've taken a quick look through and they seem good but would appreciate your confirmation!

**Comment by NickEntin** [comment]
> yay for helpful Xcode errors

Sounds about right 😂 

> Would you mind taking a quick look, especially at the test outputs (which are in Example/SnapshotTests/__Snapshots__) to make sure things are generating correctly?

Looked through the snapshot tests and everything looks good. Great work getting that put together! I'll get the PR here merged shortly and push a new version so you can depend on the subspec.

**Comment by NickEntin** [comment]
Version 0.3.1 is now available, with the Core subspec separated out! Closing this issue, since I think it should be unblocked now. Please reopen if it isn't working for you though. Thanks!

**Comment by Sherlouk** [comment]
Really appreciate your help with that Nick, I'll be sure to update my lib in due course and get it "production ready". Are you good for me to open a PR when the time is right to add a link to the README?

**Comment by NickEntin** [comment]
Sure, sounds great! 👍🏻

**Comment by NickEntin** [comment]
@Sherlouk Due to unrelated technical reasons, we've decided to transition to using SnapshotTesting internally, so I think at this point it would make sense to add `SnapshotTesting` support to this project, since it will now have first party support in addition to community support. Are you open to merging your extension into this framework as a new `SnapshotTesting` subspec at this point?

**Comment by Sherlouk** [comment]
@NickEntin 

Absolutely got no problems if you want to merge the two repos into one! 🙌🏼

Not sure if I'll have time this weekend to take a look but, if you haven't, I might be able to next weekend?

Just let me know and I can update the README and redirects to this repo 👍

**Comment by NickEntin** [comment]
@Sherlouk Awesome! 🙌  Happy to let you take it if you want, so that you show up as the author on the commits/PRs. I'm of course happy to help with it as well, if you would prefer.

**Comment by Sherlouk** [comment]
No problem leave it with me and I'll see what I can do 👍
