### ISSUE TITLE
[SUGGESTION] Reasoning of Seperate Module

### ISSUE THREAD

**Issue by onurhuseyincantay** [cashapp/AccessibilitySnapshot#94]
As I can see the framework is heavily relying on SnapshotTesting why not adding this functionality as a PR to the existing framework and creating a new one.

**Comment by NickEntin** [comment]
Hi Onur! AccessibilitySnapshot has a few separate subspecs/frameworks (depends which dependency manager you're using) to support using either SnapshotTesting or FBSnapshotTestCase as the underlying snapshot engine, and potentially could include new snapshot engines in the future. Since AccessibilitySnapshot isn't tied to a specific snapshotting framework, it's published as a standalone project.

**Comment by onurhuseyincantay** [comment]
thanks for the clarification, would be nice to add this to the readme.md to avoid similar questions coming up :)
